apiVersion: v1
kind: Secret
metadata:
  name: ldap-group-sync
  namespace: group-sync-operator
data:
  password: aTc2enFTQ3FoaEw4
  username: ZmNBREJpbmRVc2VyT0NQQw==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-ca
  namespace: group-sync-operator
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdOVENDQkIyZ0F3SUJBZ0lRRlhGRTh0Z0tnSXhJTnVqTm1zSFppekFOQmdrcWhraUc5dzBCQVFzRkFEQ0IKckRFTE1Ba0dBMVVFQmhNQ1NWUXhEakFNQmdOVkJBZ1RCVWwwWVd4NU1ROHdEUVlEVlFRSEV3WlVjbVZ1ZEc4eApGVEFUQmdOVkJBc1RERUZ5WldFZ1UybHpkR1Z0YVRFc01Db0dBMVVFQ2hNalVHaHZaVzVwZUNCSmJtWnZjbTFoCmRHbGpZU0JDWVc1allYSnBZU0JUTG5BdVFTNHhOekExQmdOVkJBTVRMbEJvYjJWdWFYZ2dTUzVDTGlCU2IyOTAKSUVObGNuUnBabWxqWVhScGIyNGdRWFYwYUc5eWFYUjVJQzBnUnpJd0hoY05NVGN3TlRFMk1UQXlNRFU1V2hjTgpORGN3TlRFMk1UQXpNRFU0V2pDQnJERUxNQWtHQTFVRUJoTUNTVlF4RGpBTUJnTlZCQWdUQlVsMFlXeDVNUTh3CkRRWURWUVFIRXdaVWNtVnVkRzh4RlRBVEJnTlZCQXNUREVGeVpXRWdVMmx6ZEdWdGFURXNNQ29HQTFVRUNoTWoKVUdodlpXNXBlQ0JKYm1admNtMWhkR2xqWVNCQ1lXNWpZWEpwWVNCVExuQXVRUzR4TnpBMUJnTlZCQU1UTGxCbwpiMlZ1YVhnZ1NTNUNMaUJTYjI5MElFTmxjblJwWm1sallYUnBiMjRnUVhWMGFHOXlhWFI1SUMwZ1J6SXdnZ0lpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRQ3R0Q3cvVUx4ejZock9PMmxYN280eDNMa0YKeUgxTlYyTE5kbVJEcDZ1ME5DSnJDc29EbHV2WWowakJKVjgvejBhSlNCVFhrTXdXU0RETTZkYStjR21nOG1zcwpBU3dyVU5Pc3U0S2t1aTA1T0RkRWpYajgrOEFvZmlORzhhZGlBNGptSGI2dzRrYVYzUTUzNmlqbmFTeXB1WFJsCnhiVUFwbW01RW1kRlV5NWRYRWNNSVlHUzg1b2hLbXJrZUhwMEpDdVhZWlN3OWlnTHNldGIvbVd3VStGTFpBK3IKYWxDM21CKzFhbTQxVHFDYWpQTGoxdkFZTCsrb09Tckt0SnlTc0MzMkFmTWp1Mk44ditxS2dJYkFHWWZINW5GTApkbXpuYnZseU5KaVYzN1dvQkkrQUNsazN6aFpXVmtrTE5NVGt6bVd1NnB0SVQrRnFtWmhwVTd2NXM1U290eS9SCjM1M0s3TlNmZFVzT2JwVk45UFNDVDdOQUd3djVxbUs1eXJCOWhYS1ZXcndxRWNpTkpBdXNSeThrNHMzanArMG4KNTJrei96MU53aWtPWXZ2ZWVDaUdxVmJhcnRJR0ViZ2ZDZS9IcGVEK1I1TVVtRmoyMk1qNktVUjZXZURxWnpSWApNcExzRXBTK0doVGxmQllMVnVMS2k2dm1vbXRQSlV0eGxRM3BxbVA3b1NTbGsyWFRDNUJDUytGM0Q1eGVhdzhaCmY2NmRwc2hLWlhwajhjZWwvTzl1RkYxOXFITWd3MHB2akhXVERaRzJEajc3M1MyOFRvb0R4S2lxT0Zhc0Q1MkMKR1orRWdiRU1TaU4zdXkwRVZoSUsyM1I4R2hobHV5VnVJYWpkMVArT0Z2OVZFT0pNMGxnb0lIVENmeWs3R1NBaApvSVRVY1pVd29nalErcXA5ZXdJREFRQUJvMUV3VHpBTEJnTlZIUThFQkFNQ0FZWXdEd1lEVlIwVEFRSC9CQVV3CkF3RUIvekFkQmdOVkhRNEVGZ1FVWG1Bb3hqZE5yZTJLb3V5OGxZb3AveGVYakpZd0VBWUpLd1lCQkFHQ054VUIKQkFNQ0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBQU5ISE1VVWpMNGxYTFl0M2ZZcWVhV2ZXdWgxUDNFcgpJVjBJbUlVaU5idTMySmhwekl2ZVZ6Yml3dE9jYWxva3JLV0lvd2pjbThxNEY4RnpKSk1uc055Tysxb0ZJejFyCmxDYWFYc2tzd0I4OUlzRFZKM2tDcm55WWxGeXoxRWlSOEhGalpHUXZuckFSUDRhSWJJaTJXdmxrWWVNNnQrdVAKb2o4TFZVa1JKWkZnY0p5NFVzVHVBU3dwVDVya29MTUhnUnhHSXZXdWlHRHJIaWFoZ3ZsNk95T0M2anRFM0xiMQpkaGVDN09MMEdYZWJlTmYwSUNjTlNqUnZjbEpJUG1KMkMrVmFLK0NzVE5XYklIWDdjZ0VqUG42SlIyakY2MU5tCitWd0xOU0poOWdxdEI4OCswTCs3UW5zdnVrVjJGemN5dzExc0FUMy94MFhBcW1UMTQ5ZG5id2plbERsT0IwOFEKTU5pSjdzbnVjekFVREgvWTUwVHRTRlhCbld6SmYyelliSUV4MkxtVTdhUGt1VUxobjVzS1dMSjRkS2p0ZzZsawpTSzZwUzJjbGJTS0p5NTlTTlFoZEZHWnFzZUJVUVVmQnRCdktMU3k4ai9DZWpMQWNMc0VrZDJZRVNFMTVGRDVCClZad3d0aDBmZE56MGJ0UHZjVnZQS2g5V3MxOENYSEh4ZzFDVmhwZkl6WXdsZ2lxVFNMamx4MXRiUnA3bURpdnUKeXlnZmhTUUh6d3hWSVdxSTV1bXVEWU9BSjc4eXB6bG1ZNVl0M1pOWi9VcnhvQ1NaTnVPM1hMOVlDbkh1V2RsTQpiMVliMHEwY2YzUFdQbWlpT09SWVc1YkpmZXBiN2lzaCtFQzJJN1M4azRkVFJwVS9FMzVzS2ZlMnloZmlMZmU3CmMwRlYrd1JmMC9FeAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQ0KTUlJR0hUQ0NCQVdnQXdJQkFnSVFhZ2hqemFWNHhMWkRRdUVWb2VxKzFUQU5CZ2txaGtpRzl3MEJBUXNGQURDQg0KbnpFTE1Ba0dBMVVFQmhNQ1NWUXhEakFNQmdOVkJBZ1RCVWwwWVd4NU1ROHdEUVlEVlFRSEV3WlVjbVZ1ZEc4eA0KSlRBakJnTlZCQXNUSEVScGNtVjZhVzl1WlNCVVpXTnVhV05oSUZSbFkyNXZiRzluYVdVeEdEQVdCZ05WQkFvVA0KRDBGc2JHbDBkV1JsSUZNdWNDNUJMakV1TUN3R0ExVUVBeE1sUVd4c2FYUjFaR1VnVW05dmRDQkRaWEowYVdacA0KWTJGMGFXOXVJRUYxZEdodmNtbDBlVEFnRncweU1EQTBNVEF4TXpJek5UZGFHQTh5TURVd01EUXhNREV6TXpNMQ0KTmxvd2daOHhDekFKQmdOVkJBWVRBa2xVTVE0d0RBWURWUVFJRXdWSmRHRnNlVEVQTUEwR0ExVUVCeE1HVkhKbA0KYm5Sdk1TVXdJd1lEVlFRTEV4eEVhWEpsZW1sdmJtVWdWR1ZqYm1sallTQlVaV051YjJ4dloybGxNUmd3RmdZRA0KVlFRS0V3OUJiR3hwZEhWa1pTQlRMbkF1UVM0eExqQXNCZ05WQkFNVEpVRnNiR2wwZFdSbElGSnZiM1FnUTJWeQ0KZEdsbWFXTmhkR2x2YmlCQmRYUm9iM0pwZEhrd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJSw0KQW9JQ0FRQ2tmSXdKMXAzajhZTnpYWGtQalAxSXZtWW95bWpQNW9VRC9YWW45S2hJaFJwZnJoRDBUa2FtdHhOZQ0KMW9BWWRqazNrbTNibk9iTkFuV3NMdWQ4NTBONzVIekIzaStkWk9xUUxaUjNDazYwaW9mY2FNbXVWRWFIRGJNZg0Kd3VNUTFJMy9BUUVBRWMrNGRkOHAwQ0xxKzFPeVFZcDBoZ3BvTlhDczBjU2pQbmV0Zk9LejhFTFd1NHhkN3daZA0KUmdvdjFXaUZyTHJLVzgyRnJOSHQ2eld2VVMyWVh3YW9zMlZwOGx1aGdrWmZnQ3VOMldGRDhjalZOTTBrcytGMw0KdEttQy9WZitBSzVnTmNpMVNoaU5xZDZwM1RPalozdmJ1QVNCaEQvcVZUN3NhVy84SGcvLzNBQ1VaZmhmV0cxYw0KRzl1UmFzMmU3NitZT3VwaUMxZ1FjTDV1ZStjbkhHb2FUdXdkZG5lSjl1OHlMZ0ZDSS8rTnRISVN0M1JIbHVoSw0KWTdGQ1FudWRmMENLaDgzMFZseG9WUUt4aVF0SXd0ayt1RzMrcllBYzNnektHbC9CUVMzU05MOUJyQzZFMzZ2MQ0KT0ttcE1Bb2F4MXhqRzhPQkN1WlpITFhybDZjMC9PbWxUTkJ4QkJaS1BoTWJHY2c5cVdpeDdTcUpWSGl4Tnk4Mw0KTzNsTWNzSEx0T2pIMXZFbExEek9QSDRGbnZxT1F3RkthWXdBUjQyUlY1K2hBOTBjL2NSOGlscWVWSjYvemNGVA0KNkNLOUJQaUtCNy9FQUhscnVpaWx1K1MvTkFCb1pTckVXaGxLdCtjdjN5UFRpR1d1TUt5bTdTRk9VL29MRTd4WA0KNlpFQnZSWXJRQWVoYmg2WHFkbVVYVHhQaGYxUWMra0E2cnE2b2trdXQ2bC80dUtaWVFJREFRQUJvMUV3VHpBTA0KQmdOVkhROEVCQU1DQVlZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXFjcDYzc1gwMDQycA0KSVdpeGNPZ0pqOERYOVZJd0VBWUpLd1lCQkFHQ054VUJCQU1DQVFBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQg0KQURHSldGNG5IZUxma1NjY1JTNlpjZGlORUdCN1F6b0tYdnNCT09YT29RU2toTG8zNHprVHhXSGlLQXhaS0duRw0KN3ZySUFDODFSaU5JSVFCaEMrVFpCSFJ4TXc3a09uWGRQUXJhUzJZbFFOZCtzR3NLYkZSUCtIMVhqTjQ1Y0JlZw0Kdm5iMGd6VzhmUUQwQmwxRXA3b2pra2VZQkxpSVZUTWNIa3VZTHI3MHlIb2cveDJkbGw2ZUoyWkU5RVkxdEtrUg0KTE15MW9BRTY2L0g0bit3YTFRTGg1L2xmdTFYS1ZjSUduVkZMSkF1MzRqVFRJRFNCUVJYYzkzY3h6Z0VPWHd1eQ0KQnU0ckNPUnAzVi9WWml3aFdMeXkrSXpBSTl6Umw2UVNvQTMydUN4dVBja1UxTFVnUmdURXNGT3NWdnl1WC96SA0KOUZNQjZGbFNiTXAzc0FrZnhkTk9rZ2FVd3NNYnRSM2VCbVBOTFcyZkdwR0hKMDJjeGlYM0UySVJ0NmRENWRlZA0KSWVSL3REQ3N5L3VvbU1oelBIN3RmdW1rVTBOd2lHMHJPL3Izd0ZmRFVrZXgrV3V6cVRZazRMU2JPYmxGMlhQSQ0Kb0h4QTVJWlgvdGhCcnRlWTdjY2dXMlJiQWxTSzJ1WTRXam1IY0RCTjhiVDl2eXpLcS81NHROWXlYQ1lwOVdidQ0KZk9JRUpUUFA4a1FmZmFIeU02ZGhFQWkyR2tOaitnd2gyQ0M2cG5ZQmhPUVQ1dmhjbG1IajF0dS9hU0JIQnd6RA0KNDIwTlhTLzNjSHFNdWZuYUc2aXZQbEJkNGYxQ2FKU2tRbXoyV3BxU1dPaVgvQjBicmNsaThCd2l0QUpMTDhuSA0KQmcyZlkrcUl4ZGdEczVieDd6N2x2WGdodWV2elh3bHNvU3JlTDc4cHA1QXQNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg==
type: Opaque

---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: ldap-groupsync
  namespace: group-sync-operator
spec:
  providers:
  - ldap:
      augmentedActiveDirectory:
        groupMembershipAttributes:
        - 'memberOf:1.2.840.113556.1.4.1941:'
        groupNameAttributes:
        - cn
        groupUIDAttribute: distinguishedName
        groupsQuery:
          baseDN: OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet
          derefAliases: never
          filter: (&(objectClass=group)(memberOf:1.2.840.113556.1.4.1941:=CN=cluster-ocp-integrazione-trento-01-filtro-accesso-cluster,OU=cluster-ocp-integrazione-trento-01,OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet))
          scope: sub
        userNameAttributes:
        - sAMAccountName
        usersQuery:
          baseDN: ou=Accounts,dc=fc,dc=dir,dc=crtnet
          derefAliases: never
          filter: (objectclass=person)
          pageSize: 0
          scope: sub
      caSecret:
        key: ca.crt
        kind: Secret
        name: ldap-ca
        namespace: group-sync-operator
      credentialsSecret:
        kind: Secret
        name: ldap-group-sync
        namespace: group-sync-operator
      insecure: false
      prune: true
      url: ldaps://ldap.fc.dir.crtnet
      whitelist:
        - CN=cluster-ocp-integrazione-trento-01-ruolo-cluster-admin,OU=cluster-ocp-integrazione-trento-01,OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet
    name: ldap
  schedule: '*/3 * * * *'

