apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGHTCCBAWgAwIBAgIQaghjzaV4xLZDQuEVoeq+1TANBgkqhkiG9w0BAQsFADCB
    nzELMAkGA1UEBhMCSVQxDjAMBgNVBAgTBUl0YWx5MQ8wDQYDVQQHEwZUcmVudG8x
    JTAjBgNVBAsTHERpcmV6aW9uZSBUZWNuaWNhIFRlY25vbG9naWUxGDAWBgNVBAoT
    D0FsbGl0dWRlIFMucC5BLjEuMCwGA1UEAxMlQWxsaXR1ZGUgUm9vdCBDZXJ0aWZp
    Y2F0aW9uIEF1dGhvcml0eTAgFw0yMDA0MTAxMzIzNTdaGA8yMDUwMDQxMDEzMzM1
    NlowgZ8xCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTEPMA0GA1UEBxMGVHJl
    bnRvMSUwIwYDVQQLExxEaXJlemlvbmUgVGVjbmljYSBUZWNub2xvZ2llMRgwFgYD
    VQQKEw9BbGxpdHVkZSBTLnAuQS4xLjAsBgNVBAMTJUFsbGl0dWRlIFJvb3QgQ2Vy
    dGlmaWNhdGlvbiBBdXRob3JpdHkwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
    AoICAQCkfIwJ1p3j8YNzXXkPjP1IvmYoymjP5oUD/XYn9KhIhRpfrhD0TkamtxNe
    1oAYdjk3km3bnObNAnWsLud850N75HzB3i+dZOqQLZR3Ck60iofcaMmuVEaHDbMf
    wuMQ1I3/AQEAEc+4dd8p0CLq+1OyQYp0hgpoNXCs0cSjPnetfOKz8ELWu4xd7wZd
    Rgov1WiFrLrKW82FrNHt6zWvUS2YXwaos2Vp8luhgkZfgCuN2WFD8cjVNM0ks+F3
    tKmC/Vf+AK5gNci1ShiNqd6p3TOjZ3vbuASBhD/qVT7saW/8Hg//3ACUZfhfWG1c
    G9uRas2e76+YOupiC1gQcL5ue+cnHGoaTuwddneJ9u8yLgFCI/+NtHISt3RHluhK
    Y7FCQnudf0CKh830VlxoVQKxiQtIwtk+uG3+rYAc3gzKGl/BQS3SNL9BrC6E36v1
    OKmpMAoax1xjG8OBCuZZHLXrl6c0/OmlTNBxBBZKPhMbGcg9qWix7SqJVHixNy83
    O3lMcsHLtOjH1vElLDzOPH4FnvqOQwFKaYwAR42RV5+hA90c/cR8ilqeVJ6/zcFT
    6CK9BPiKB7/EAHlruiilu+S/NABoZSrEWhlKt+cv3yPTiGWuMKym7SFOU/oLE7xX
    6ZEBvRYrQAehbh6XqdmUXTxPhf1Qc+kA6rq6okkut6l/4uKZYQIDAQABo1EwTzAL
    BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUqcp63sX0042p
    IWixcOgJj8DX9VIwEAYJKwYBBAGCNxUBBAMCAQAwDQYJKoZIhvcNAQELBQADggIB
    ADGJWF4nHeLfkSccRS6ZcdiNEGB7QzoKXvsBOOXOoQSkhLo34zkTxWHiKAxZKGnG
    7vrIAC81RiNIIQBhC+TZBHRxMw7kOnXdPQraS2YlQNd+sGsKbFRP+H1XjN45cBeg
    vnb0gzW8fQD0Bl1Ep7ojkkeYBLiIVTMcHkuYLr70yHog/x2dll6eJ2ZE9EY1tKkR
    LMy1oAE66/H4n+wa1QLh5/lfu1XKVcIGnVFLJAu34jTTIDSBQRXc93cxzgEOXwuy
    Bu4rCORp3V/VZiwhWLyy+IzAI9zRl6QSoA32uCxuPckU1LUgRgTEsFOsVvyuX/zH
    9FMB6FlSbMp3sAkfxdNOkgaUwsMbtR3eBmPNLW2fGpGHJ02cxiX3E2IRt6dD5ded
    IeR/tDCsy/uomMhzPH7tfumkU0NwiG0rO/r3wFfDUkex+WuzqTYk4LSbOblF2XPI
    oHxA5IZX/thBrteY7ccgW2RbAlSK2uY4WjmHcDBN8bT9vyzKq/54tNYyXCYp9Wbu
    fOIEJTPP8kQffaHyM6dhEAi2GkNj+gwh2CC6pnYBhOQT5vhclmHj1tu/aSBHBwzD
    420NXS/3cHqMufnaG6ivPlBd4f1CaJSkQmz2WpqSWOiX/B0brcli8BwitAJLL8nH
    Bg2fY+qIxdgDs5bx7z7lvXghuevzXwlsoSreL78pp5At
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIGNTCCBB2gAwIBAgIQFXFE8tgKgIxINujNmsHZizANBgkqhkiG9w0BAQsFADCB
    rDELMAkGA1UEBhMCSVQxDjAMBgNVBAgTBUl0YWx5MQ8wDQYDVQQHEwZUcmVudG8x
    FTATBgNVBAsTDEFyZWEgU2lzdGVtaTEsMCoGA1UEChMjUGhvZW5peCBJbmZvcm1h
    dGljYSBCYW5jYXJpYSBTLnAuQS4xNzA1BgNVBAMTLlBob2VuaXggSS5CLiBSb290
    IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzIwHhcNMTcwNTE2MTAyMDU5WhcN
    NDcwNTE2MTAzMDU4WjCBrDELMAkGA1UEBhMCSVQxDjAMBgNVBAgTBUl0YWx5MQ8w
    DQYDVQQHEwZUcmVudG8xFTATBgNVBAsTDEFyZWEgU2lzdGVtaTEsMCoGA1UEChMj
    UGhvZW5peCBJbmZvcm1hdGljYSBCYW5jYXJpYSBTLnAuQS4xNzA1BgNVBAMTLlBo
    b2VuaXggSS5CLiBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzIwggIi
    MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCttCw/ULxz6hrOO2lX7o4x3LkF
    yH1NV2LNdmRDp6u0NCJrCsoDluvYj0jBJV8/z0aJSBTXkMwWSDDM6da+cGmg8mss
    ASwrUNOsu4Kkui05ODdEjXj8+8AofiNG8adiA4jmHb6w4kaV3Q536ijnaSypuXRl
    xbUApmm5EmdFUy5dXEcMIYGS85ohKmrkeHp0JCuXYZSw9igLsetb/mWwU+FLZA+r
    alC3mB+1am41TqCajPLj1vAYL++oOSrKtJySsC32AfMju2N8v+qKgIbAGYfH5nFL
    dmznbvlyNJiV37WoBI+AClk3zhZWVkkLNMTkzmWu6ptIT+FqmZhpU7v5s5Soty/R
    353K7NSfdUsObpVN9PSCT7NAGwv5qmK5yrB9hXKVWrwqEciNJAusRy8k4s3jp+0n
    52kz/z1NwikOYvveeCiGqVbartIGEbgfCe/HpeD+R5MUmFj22Mj6KUR6WeDqZzRX
    MpLsEpS+GhTlfBYLVuLKi6vmomtPJUtxlQ3pqmP7oSSlk2XTC5BCS+F3D5xeaw8Z
    f66dpshKZXpj8cel/O9uFF19qHMgw0pvjHWTDZG2Dj773S28TooDxKiqOFasD52C
    GZ+EgbEMSiN3uy0EVhIK23R8GhhluyVuIajd1P+OFv9VEOJM0lgoIHTCfyk7GSAh
    oITUcZUwogjQ+qp9ewIDAQABo1EwTzALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUw
    AwEB/zAdBgNVHQ4EFgQUXmAoxjdNre2Kouy8lYop/xeXjJYwEAYJKwYBBAGCNxUB
    BAMCAQAwDQYJKoZIhvcNAQELBQADggIBAANHHMUUjL4lXLYt3fYqeaWfWuh1P3Er
    IV0ImIUiNbu32JhpzIveVzbiwtOcalokrKWIowjcm8q4F8FzJJMnsNyO+1oFIz1r
    lCaaXskswB89IsDVJ3kCrnyYlFyz1EiR8HFjZGQvnrARP4aIbIi2WvlkYeM6t+uP
    oj8LVUkRJZFgcJy4UsTuASwpT5rkoLMHgRxGIvWuiGDrHiahgvl6OyOC6jtE3Lb1
    dheC7OL0GXebeNf0ICcNSjRvclJIPmJ2C+VaK+CsTNWbIHX7cgEjPn6JR2jF61Nm
    +VwLNSJh9gqtB88+0L+7QnsvukV2Fzcyw11sAT3/x0XAqmT149dnbwjelDlOB08Q
    MNiJ7snuczAUDH/Y50TtSFXBnWzJf2zYbIEx2LmU7aPkuULhn5sKWLJ4dKjtg6lk
    SK6pS2clbSKJy59SNQhdFGZqseBUQUfBtBvKLSy8j/CejLAcLsEkd2YESE15FD5B
    VZwwth0fdNz0btPvcVvPKh9Ws18CXHHxg1CVhpfIzYwlgiqTSLjlx1tbRp7mDivu
    yygfhSQHzwxVIWqI5umuDYOAJ78ypzlmY5Yt3ZNZ/UrxoCSZNuO3XL9YCnHuWdlM
    b1Yb0q0cf3PWPmiiOORYW5bJfepb7ish+EC2I7S8k4dTRpU/E35sKfe2yhfiLfe7
    c0FV+wRf0/Ex
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: user-ca-bundle
  namespace: openshift-config
---
apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  name: cluster
spec:
  trustedCA:
    name: user-ca-bundle
