apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-metallb
policyDefaults:
  namespace: policies
  placement:
    placementRulePath: placement.yaml
  remediationAction: enforce
policies:
  - name: install-metallb
    manifests:
      - path: metallb-operator.yaml

