ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
AUTHENTICATION_TYPE: LDAP
AVATAR_KIND: local
DEFAULT_TAG_EXPIRATION: 2w
ENTERPRISE_LOGO_URL: /static/img/quay-horizontal-color.svg
EXTERNAL_TLS_TERMINATION: true
FEATURE_ACTION_LOG_ROTATION: false
FEATURE_ANONYMOUS_ACCESS: false
FEATURE_APP_SPECIFIC_TOKENS: true
FEATURE_BITBUCKET_BUILD: false
FEATURE_BLACKLISTED_EMAILS: false
FEATURE_BUILD_SUPPORT: false
FEATURE_CHANGE_TAG_EXPIRATION: true
FEATURE_DIRECT_LOGIN: true
FEATURE_EXTENDED_REPOSITORY_NAMES: true
FEATURE_FIPS: false
FEATURE_GITHUB_BUILD: false
FEATURE_GITHUB_LOGIN: false
FEATURE_GITLAB_BUILD: false
FEATURE_GOOGLE_LOGIN: false
FEATURE_INVITE_ONLY_USER_CREATION: false
FEATURE_MAILING: false
FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: false
FEATURE_PARTIAL_USER_AUTOCOMPLETE: true
FEATURE_PROXY_STORAGE: true
FEATURE_SECURITY_NOTIFICATIONS: true
FEATURE_TEAM_SYNCING: true
FEATURE_USER_CREATION: true
FEATURE_USER_LAST_ACCESSED: true
FEATURE_USER_LOG_ACCESS: false
FEATURE_USER_METADATA: false
FEATURE_USER_RENAME: false
FEATURE_USERNAME_CONFIRMATION: true
FRESH_LOGIN_TIMEOUT: 10m
GITHUB_LOGIN_CONFIG: {}
GITHUB_TRIGGER_CONFIG: {}
GITLAB_TRIGGER_KIND: {}
LDAP_ADMIN_DN: cn=fcADBindUserOCPP,ou=_Technical,ou=Accounts,dc=fc,dc=dir,dc=crtnet
LDAP_ADMIN_PASSWD: sqRgcsQunqMKpuN
LDAP_ALLOW_INSECURE_FALLBACK: false
LDAP_BASE_DN:
- dc=fc
- dc=dir
- dc=crtnet
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: sAMAccountName
LDAP_URI: ldaps://ldap.fc.dir.crtnet:636
LDAP_USER_FILTER: "(&(objectClass=user)(memberOf:1.2.840.113556.1.4.1941:=CN=quay-login-filter,OU=quay.io,OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet))"
LDAP_USER_RDN:
- ou=Accounts
SUPER_USERS:
  - fc0236
  - fc0816
  - fc0925
  - fcef69
  - fcee35
LOGS_MODEL: database
LOGS_MODEL_CONFIG: {}
MAIL_DEFAULT_SENDER: quay-openshift-infra-cert@allitude.it
MAIL_PORT: 25
MAIL_SERVER: smtp.crtnet
MAIL_USE_AUTH: false
MAIL_USE_TLS: false
PREFERRED_URL_SCHEME: https
REGISTRY_TITLE: Quay Allitude
REGISTRY_TITLE_SHORT: Quay
SEARCH_MAX_RESULT_PAGE_COUNT: 10
SEARCH_RESULTS_PER_PAGE: 10
SERVER_HOSTNAME: registry-quay.apps.fcakit01.infra-cert.enet
SETUP_COMPLETE: true
TAG_EXPIRATION_OPTIONS:
- 2w
TEAM_RESYNC_STALE_TIME: 60m
TESTING: false
USER_RECOVERY_TOKEN_LIFETIME: 30m

