appConfig:
  destinationServer:
    name: "sviluppo"
    url: "https://api.fcakst01.sviluppo.enet:6443"
  revision: main
  forwarding:
    splunk:
      # Specify Splunk HEC Token and Index
      token: 0a128a61-22ed-4a74-ad16-406713d65670
      hostname: fcvlsfc1.log.collaudo.servizi.allitude.it 
