apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: metallb-config
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      vendor: "OpenShift"
  remediationAction: enforce
policies:
  - name: metallb-config 
    manifests:
      - path: metallb-config.yaml

