---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-ldap-ca
  namespace: group-sync-operator
spec:
  secretStoreRef:
    name: vault-allitude-windows
    kind: ClusterSecretStore
  target:
    name: vault-ldap-ca
  dataFrom:
  - extract:
      key: certificati/phoenix-rootca-g2
      decodingStrategy: Auto

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-ldap-group-sync
  namespace: group-sync-operator
spec:
  secretStoreRef:
    name: vault-allitude-windows
    kind: ClusterSecretStore
  target:
    name: vault-ldap-group-sync
  dataFrom:
  - extract:
      key: active-directory/fcdb/fcadbinduserocpc
      decodingStrategy: None

