apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: groups-sync-external-secrets-config
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      vendor: "OpenShift"
  remediationAction: enforce
policies:
  - name: groups-sync-external-secrets-config
    manifests:
      - path: groups-sync-external-secrets.yaml

