apiVersion: v1
kind: Secret
metadata:
  name: ldap-group-sync
  namespace: group-sync-operator
data:
  password: c3FSZ2NzUXVucU1LcHVO
  username: ZmNBREJpbmRVc2VyT0NQUA==
type: Opaque
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: ldap-groupsync
  namespace: group-sync-operator
spec:
  providers:
  - ldap:
      augmentedActiveDirectory:
        groupMembershipAttributes:
        - 'memberOf:1.2.840.113556.1.4.1941:'
        groupNameAttributes:
        - cn
        groupUIDAttribute: distinguishedName
        groupsQuery:
          baseDN: OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet
          derefAliases: never
          filter: (&(objectClass=group)(memberOf:1.2.840.113556.1.4.1941:=CN=ocp-produzione-accesso-cluster,OU=ocp-produzione,OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet))
          scope: sub
        userNameAttributes:
        - sAMAccountName
        usersQuery:
          baseDN: ou=Accounts,dc=fc,dc=dir,dc=crtnet
          derefAliases: never
          filter: (objectclass=person)
          pageSize: 0
          scope: sub
      caSecret:
        key: ca.crt
        kind: Secret
        name: ldap-ca
        namespace: group-sync-operator
      credentialsSecret:
        kind: Secret
        name: ldap-group-sync
        namespace: group-sync-operator
      insecure: false
      prune: true
      url: ldaps://ldap.fc.dir.crtnet
      whitelist:
      - CN=ocp-produzione-ruolo-amministratori,OU=ocp-produzione,OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet
      - CN=ocp-produzione-ruolo-gestione,OU=ocp-produzione,OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet
      - CN=ocp-produzione-ruolo-sviluppatori,OU=ocp-produzione,OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet
      - CN=ocp-produzione-ruolo-assistenza,OU=ocp-produzione,OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet
      - CN=ocp-produzione-ruolo-test,OU=ocp-produzione,OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet
      - CN=ocp-produzione-ruolo-supervisione,OU=ocp-produzione,OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet
    name: ldap
  schedule: '*/3 * * * *'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ocp-produzione-ruolo-amministratori
