apiVersion: v1
kind: Secret
metadata:
  name: ldap-secret
  namespace: openshift-config
type: Opaque
data:
  bindPassword: "aTc2enFTQ3FoaEw4"
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  identityProviders:
  - ldap:
      attributes:
        email:
        - mail
        id:
        - distinguishedName
        name:
        - cn
        preferredUsername:
        - sAMAccountName
      bindDN: cn=fcADBindUserOCPC,ou=_Technical,ou=Accounts,dc=fc,dc=dir,dc=crtnet
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: ldaps://ldap.fc.dir.crtnet/dc=fc,dc=dir,dc=crtnet?sAMAccountName?sub?(&(objectClass=user)(memberOf:1.2.840.113556.1.4.1941:=CN=cluster-ocp-integrazione-trento-01-filtro-accesso-cluster,OU=cluster-ocp-integrazione-trento-01,OU=k8sFunctions,OU=Functions,OU=Accounts,DC=fc,DC=dir,DC=crtnet))
    mappingMethod: claim
    name: ldapidp
    type: LDAP
---

apiVersion: v1
data:
  ca.crt: "-----BEGIN CERTIFICATE-----\nMIIGNTCCBB2gAwIBAgIQFXFE8tgKgIxINujNmsHZizANBgkqhkiG9w0BAQsFADCB\nrDELMAkGA1UEBhMCSVQxDjAMBgNVBAgTBUl0YWx5MQ8wDQYDVQQHEwZUcmVudG8x\nFTATBgNVBAsTDEFyZWEgU2lzdGVtaTEsMCoGA1UEChMjUGhvZW5peCBJbmZvcm1h\ndGljYSBCYW5jYXJpYSBTLnAuQS4xNzA1BgNVBAMTLlBob2VuaXggSS5CLiBSb290\nIENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzIwHhcNMTcwNTE2MTAyMDU5WhcN\nNDcwNTE2MTAzMDU4WjCBrDELMAkGA1UEBhMCSVQxDjAMBgNVBAgTBUl0YWx5MQ8w\nDQYDVQQHEwZUcmVudG8xFTATBgNVBAsTDEFyZWEgU2lzdGVtaTEsMCoGA1UEChMj\nUGhvZW5peCBJbmZvcm1hdGljYSBCYW5jYXJpYSBTLnAuQS4xNzA1BgNVBAMTLlBo\nb2VuaXggSS5CLiBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzIwggIi\nMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCttCw/ULxz6hrOO2lX7o4x3LkF\nyH1NV2LNdmRDp6u0NCJrCsoDluvYj0jBJV8/z0aJSBTXkMwWSDDM6da+cGmg8mss\nASwrUNOsu4Kkui05ODdEjXj8+8AofiNG8adiA4jmHb6w4kaV3Q536ijnaSypuXRl\nxbUApmm5EmdFUy5dXEcMIYGS85ohKmrkeHp0JCuXYZSw9igLsetb/mWwU+FLZA+r\nalC3mB+1am41TqCajPLj1vAYL++oOSrKtJySsC32AfMju2N8v+qKgIbAGYfH5nFL\ndmznbvlyNJiV37WoBI+AClk3zhZWVkkLNMTkzmWu6ptIT+FqmZhpU7v5s5Soty/R\n353K7NSfdUsObpVN9PSCT7NAGwv5qmK5yrB9hXKVWrwqEciNJAusRy8k4s3jp+0n\n52kz/z1NwikOYvveeCiGqVbartIGEbgfCe/HpeD+R5MUmFj22Mj6KUR6WeDqZzRX\nMpLsEpS+GhTlfBYLVuLKi6vmomtPJUtxlQ3pqmP7oSSlk2XTC5BCS+F3D5xeaw8Z\nf66dpshKZXpj8cel/O9uFF19qHMgw0pvjHWTDZG2Dj773S28TooDxKiqOFasD52C\nGZ+EgbEMSiN3uy0EVhIK23R8GhhluyVuIajd1P+OFv9VEOJM0lgoIHTCfyk7GSAh\noITUcZUwogjQ+qp9ewIDAQABo1EwTzALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUw\nAwEB/zAdBgNVHQ4EFgQUXmAoxjdNre2Kouy8lYop/xeXjJYwEAYJKwYBBAGCNxUB\nBAMCAQAwDQYJKoZIhvcNAQELBQADggIBAANHHMUUjL4lXLYt3fYqeaWfWuh1P3Er\nIV0ImIUiNbu32JhpzIveVzbiwtOcalokrKWIowjcm8q4F8FzJJMnsNyO+1oFIz1r\nlCaaXskswB89IsDVJ3kCrnyYlFyz1EiR8HFjZGQvnrARP4aIbIi2WvlkYeM6t+uP\noj8LVUkRJZFgcJy4UsTuASwpT5rkoLMHgRxGIvWuiGDrHiahgvl6OyOC6jtE3Lb1\ndheC7OL0GXebeNf0ICcNSjRvclJIPmJ2C+VaK+CsTNWbIHX7cgEjPn6JR2jF61Nm\n+VwLNSJh9gqtB88+0L+7QnsvukV2Fzcyw11sAT3/x0XAqmT149dnbwjelDlOB08Q\nMNiJ7snuczAUDH/Y50TtSFXBnWzJf2zYbIEx2LmU7aPkuULhn5sKWLJ4dKjtg6lk\nSK6pS2clbSKJy59SNQhdFGZqseBUQUfBtBvKLSy8j/CejLAcLsEkd2YESE15FD5B\nVZwwth0fdNz0btPvcVvPKh9Ws18CXHHxg1CVhpfIzYwlgiqTSLjlx1tbRp7mDivu\nyygfhSQHzwxVIWqI5umuDYOAJ78ypzlmY5Yt3ZNZ/UrxoCSZNuO3XL9YCnHuWdlM\nb1Yb0q0cf3PWPmiiOORYW5bJfepb7ish+EC2I7S8k4dTRpU/E35sKfe2yhfiLfe7\nc0FV+wRf0/Ex\n-----END
    CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\r\nMIIGHTCCBAWgAwIBAgIQaghjzaV4xLZDQuEVoeq+1TANBgkqhkiG9w0BAQsFADCB\r\nnzELMAkGA1UEBhMCSVQxDjAMBgNVBAgTBUl0YWx5MQ8wDQYDVQQHEwZUcmVudG8x\r\nJTAjBgNVBAsTHERpcmV6aW9uZSBUZWNuaWNhIFRlY25vbG9naWUxGDAWBgNVBAoT\r\nD0FsbGl0dWRlIFMucC5BLjEuMCwGA1UEAxMlQWxsaXR1ZGUgUm9vdCBDZXJ0aWZp\r\nY2F0aW9uIEF1dGhvcml0eTAgFw0yMDA0MTAxMzIzNTdaGA8yMDUwMDQxMDEzMzM1\r\nNlowgZ8xCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTEPMA0GA1UEBxMGVHJl\r\nbnRvMSUwIwYDVQQLExxEaXJlemlvbmUgVGVjbmljYSBUZWNub2xvZ2llMRgwFgYD\r\nVQQKEw9BbGxpdHVkZSBTLnAuQS4xLjAsBgNVBAMTJUFsbGl0dWRlIFJvb3QgQ2Vy\r\ndGlmaWNhdGlvbiBBdXRob3JpdHkwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK\r\nAoICAQCkfIwJ1p3j8YNzXXkPjP1IvmYoymjP5oUD/XYn9KhIhRpfrhD0TkamtxNe\r\n1oAYdjk3km3bnObNAnWsLud850N75HzB3i+dZOqQLZR3Ck60iofcaMmuVEaHDbMf\r\nwuMQ1I3/AQEAEc+4dd8p0CLq+1OyQYp0hgpoNXCs0cSjPnetfOKz8ELWu4xd7wZd\r\nRgov1WiFrLrKW82FrNHt6zWvUS2YXwaos2Vp8luhgkZfgCuN2WFD8cjVNM0ks+F3\r\ntKmC/Vf+AK5gNci1ShiNqd6p3TOjZ3vbuASBhD/qVT7saW/8Hg//3ACUZfhfWG1c\r\nG9uRas2e76+YOupiC1gQcL5ue+cnHGoaTuwddneJ9u8yLgFCI/+NtHISt3RHluhK\r\nY7FCQnudf0CKh830VlxoVQKxiQtIwtk+uG3+rYAc3gzKGl/BQS3SNL9BrC6E36v1\r\nOKmpMAoax1xjG8OBCuZZHLXrl6c0/OmlTNBxBBZKPhMbGcg9qWix7SqJVHixNy83\r\nO3lMcsHLtOjH1vElLDzOPH4FnvqOQwFKaYwAR42RV5+hA90c/cR8ilqeVJ6/zcFT\r\n6CK9BPiKB7/EAHlruiilu+S/NABoZSrEWhlKt+cv3yPTiGWuMKym7SFOU/oLE7xX\r\n6ZEBvRYrQAehbh6XqdmUXTxPhf1Qc+kA6rq6okkut6l/4uKZYQIDAQABo1EwTzAL\r\nBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUqcp63sX0042p\r\nIWixcOgJj8DX9VIwEAYJKwYBBAGCNxUBBAMCAQAwDQYJKoZIhvcNAQELBQADggIB\r\nADGJWF4nHeLfkSccRS6ZcdiNEGB7QzoKXvsBOOXOoQSkhLo34zkTxWHiKAxZKGnG\r\n7vrIAC81RiNIIQBhC+TZBHRxMw7kOnXdPQraS2YlQNd+sGsKbFRP+H1XjN45cBeg\r\nvnb0gzW8fQD0Bl1Ep7ojkkeYBLiIVTMcHkuYLr70yHog/x2dll6eJ2ZE9EY1tKkR\r\nLMy1oAE66/H4n+wa1QLh5/lfu1XKVcIGnVFLJAu34jTTIDSBQRXc93cxzgEOXwuy\r\nBu4rCORp3V/VZiwhWLyy+IzAI9zRl6QSoA32uCxuPckU1LUgRgTEsFOsVvyuX/zH\r\n9FMB6FlSbMp3sAkfxdNOkgaUwsMbtR3eBmPNLW2fGpGHJ02cxiX3E2IRt6dD5ded\r\nIeR/tDCsy/uomMhzPH7tfumkU0NwiG0rO/r3wFfDUkex+WuzqTYk4LSbOblF2XPI\r\noHxA5IZX/thBrteY7ccgW2RbAlSK2uY4WjmHcDBN8bT9vyzKq/54tNYyXCYp9Wbu\r\nfOIEJTPP8kQffaHyM6dhEAi2GkNj+gwh2CC6pnYBhOQT5vhclmHj1tu/aSBHBwzD\r\n420NXS/3cHqMufnaG6ivPlBd4f1CaJSkQmz2WpqSWOiX/B0brcli8BwitAJLL8nH\r\nBg2fY+qIxdgDs5bx7z7lvXghuevzXwlsoSreL78pp5At\r\n-----END
    CERTIFICATE-----\r\n"
kind: ConfigMap
metadata:
  name: ca-config-map
  namespace: openshift-config
