apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secret-puller
  namespace: openshift-ingress
---      
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ingress-external-secrets
  namespace: openshift-ingress
spec:
  secretStoreRef:
    name: vault-allitude-ocp
    kind: ClusterSecretStore
  target:
    name: vault-wildcard
    template:
      type: kubernetes.io/tls
  dataFrom:
  - extract: 
      key: infra-trento-01/certificati/apps-wildcard 
      decodingStrategy: Auto




