---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: vault-binding
  namespace: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: vault-secret-puller
  namespace: openshift-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: vault-secret-puller
  namespace: group-sync-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: vault-secret-puller
  namespace: openshift-ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-binding
  namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-allitude-windows
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: ocp-infra-trento-01
          role: cluster-ocp-infra-trento-01
          serviceAccountRef:
            name: vault-secret-puller
      path: kv_windows
      server: https://vault.servizi.allitude.it
      version: v2

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-allitude-ocp
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: ocp-infra-trento-01
          role: cluster-ocp-infra-trento-01
          serviceAccountRef:
            name: vault-secret-puller
      path: kv_ocp
      server: https://vault.servizi.allitude.it
      version: v2
---
kind: OperatorConfig
apiVersion: operator.external-secrets.io/v1alpha1
metadata:
  name: external-secrets-operator-config
  namespace: external-secrets
spec:
  affinity: {}
  certController:
    affinity: {}
    create: true
    deploymentAnnotations: {}
    extraArgs: {}
    extraEnv: []
    fullnameOverride: ''
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/external-secrets/external-secrets
      tag: ''
    imagePullSecrets: []
    nameOverride: ''
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    priorityClassName: ''
    prometheus:
      enabled: false
      service:
        port: 8080
    rbac:
      create: true
    requeueInterval: 5m
    resources: {}
    securityContext: {}
    serviceAccount:
      annotations: {}
      create: true
      name: ''
    tolerations: []
  concurrent: 1
  controllerClass: ''
  crds:
    createClusterExternalSecret: true
    createClusterSecretStore: true
  createOperator: true
  deploymentAnnotations: {}
  extraArgs: {}
  extraEnv: []
  fullnameOverride: ''
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/external-secrets/external-secrets
    tag: ''
  imagePullSecrets: []
  installCRDs: false
  leaderElect: false
  nameOverride: ''
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  priorityClassName: ''
  processClusterExternalSecret: true
  processClusterStore: true
  prometheus:
    enabled: false
    service:
      port: 8080
  rbac:
    create: true
  replicaCount: 1
  resources: {}
  scopedNamespace: ''
  scopedRBAC: false
  securityContext: {}
  serviceAccount:
    annotations: {}
    create: true
    name: ''
  tolerations: []
  webhook:
    affinity: {}
    certCheckInterval: 5m
    certDir: /tmp/certs
    create: true
    deploymentAnnotations: {}
    extraArgs: {}
    extraEnv: []
    fullnameOverride: ''
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/external-secrets/external-secrets
      tag: ''
    imagePullSecrets: []
    nameOverride: ''
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    priorityClassName: ''
    prometheus:
      enabled: false
      service:
        port: 8080
    rbac:
      create: true
    replicaCount: 1
    resources: {}
    securityContext: {}
    serviceAccount:
      annotations: {}
      create: true
      name: ''
    tolerations: []


