apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: external-secrets-config
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      vendor: "OpenShift"
  remediationAction: enforce
policies:
  - name: external-secrets-config
    manifests:
      - path: external-secrets-config.yaml 

