apiVersion: v1
data:
  ca-bundle.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlJSFRDQ0JnV2dBd0lCQWdJVEZBQUFBQUkzNFpCTC9qdjc5UUFBQUFBQUFqQU5CZ2txaGtpRzl3MEJBUXNGDQpBRENCbnpFTE1Ba0dBMVVFQmhNQ1NWUXhEakFNQmdOVkJBZ1RCVWwwWVd4NU1ROHdEUVlEVlFRSEV3WlVjbVZ1DQpkRzh4SlRBakJnTlZCQXNUSEVScGNtVjZhVzl1WlNCVVpXTnVhV05oSUZSbFkyNXZiRzluYVdVeEdEQVdCZ05WDQpCQW9URDBGc2JHbDBkV1JsSUZNdWNDNUJMakV1TUN3R0ExVUVBeE1sUVd4c2FYUjFaR1VnVW05dmRDQkRaWEowDQphV1pwWTJGMGFXOXVJRUYxZEdodmNtbDBlVEFlRncweU1EQTBNVFF4TWpBeE1ERmFGdzB6TlRBME1UUXhNakV4DQpNREZhTUlHbE1Rc3dDUVlEVlFRR0V3SkpWREVPTUF3R0ExVUVDQk1GU1hSaGJIa3hEekFOQmdOVkJBY1RCbFJ5DQpaVzUwYnpFWU1CWUdBMVVFQ2hNUFFXeHNhWFIxWkdVZ1V5NXdMa0V1TVNVd0l3WURWUVFMRXh4RWFYSmxlbWx2DQpibVVnVkdWamJtbGpZU0JVWldOdWIyeHZaMmxsTVRRd01nWURWUVFERXl0QmJHeHBkSFZrWlNCRmJuUmxjbkJ5DQphWE5sSUVObGNuUnBabWxqWVhScGIyNGdRWFYwYUc5eWFYUjVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DDQpBUThBTUlJQkNnS0NBUUVBbjdHaDdCQWFvc0hJREowOGJNaHlSRUJnRjhhU1pHM2hieSthdkdJci91MFdiUUlFDQplWS9lbXh5bis5aFBVQXhoMjNza3Y1Qm82bkZGVU1qYjZJZkN6Y3JRSzhtQWxMdGRWMFhVMTJhYXo2S1RhUUVsDQplVFhGQ0ZWRFJsd0pzc1Fpa0VZYnNxMkZsaGNXeU9ndVAyTVRORE1QMWJTVzh3NXR4WDZYelJ1eGQzZktQNHU3DQp5Vkd0REU3RHBlakt3UU82cTd6cjVJUXNzY0ppcExacWNNUDNGTkh2MnE1TjN4dVhCWDR4NE9oQWU0MDJyaU9EDQo5b0w5RzJ2cFJHdXY3RUJMN09NekROTmhVMDhsU2pocVpLcmdwYnErN2swK1hBbkFWVHpxMXZkMFQ5eVpmTWFRDQpKdUtBalE2aU5HdUVBZmFBQWN1MVJkeU00VlBoMjYycm9OK1JFUUlEQVFBQm80SURTRENDQTBRd0VBWUpLd1lCDQpCQUdDTnhVQkJBTUNBUUF3SFFZRFZSME9CQllFRkN5SWZHb1dsdGlpTDNEK3lleXR6WVBxNm9tbE1JSHRCZ05WDQpIU0FFZ2VVd2dlSXdnZDhHQ1NzR0FRUUJnamNWS3pDQjBUQ0JrZ1lJS3dZQkJRVUhBZ0l3Z1lVZWdZSUFRd0JsDQpBSElBZEFCcEFHWUFhUUJqQUdFQWRBQmxBQ0FBVUFCeUFHRUFZd0IwQUdrQVl3QmxBQ0FBVXdCMEFHRUFkQUJsDQpBRzBBWlFCdUFIUUFJQUFvQUVNQVVBQlRBQ2tBSUFCRkFHNEFkQUJsQUhJQWNBQnlBR2tBY3dCbEFDQUFMUUFnDQpBRUVBYkFCc0FHa0FkQUIxQUdRQVpRQWdBRk1BTGdCd0FDNEFRUUF1TURvR0NDc0dBUVVGQndJQkZpNW9kSFJ3DQpPaTh2WTJGbVkyUmlNaTV6WlhKMmFYcHBMbUZzYkdsMGRXUmxMbWwwTDNCcmFTOWpjSE11Y0dSbU1Ca0dDU3NHDQpBUVFCZ2pjVUFnUU1IZ29BVXdCMUFHSUFRd0JCTUFzR0ExVWREd1FFQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHDQpBUUgvQWdFQU1COEdBMVVkSXdRWU1CYUFGS25LZXQ3RjlOT05xU0Zvc1hEb0NZL0ExL1ZTTUlIV0JnTlZIUjhFDQpnYzR3Z2Nzd2djaWdnY1dnZ2NLR1gyaDBkSEE2THk5allYSnZiM1F4TG5ObGNuWnBlbWt1WVd4c2FYUjFaR1V1DQphWFF2VUV0SkxVRnNiR2wwZFdSbEwwRnNiR2wwZFdSbEpUSXdVbTl2ZENVeU1FTmxjblJwWm1sallYUnBiMjRsDQpNakJCZFhSb2IzSnBkSGt1WTNKc2hsOW9kSFJ3T2k4dlkyRnliMjkwTWk1elpYSjJhWHBwTG1Gc2JHbDBkV1JsDQpMbWwwTDFCTFNTMUJiR3hwZEhWa1pTOUJiR3hwZEhWa1pTVXlNRkp2YjNRbE1qQkRaWEowYVdacFkyRjBhVzl1DQpKVEl3UVhWMGFHOXlhWFI1TG1OeWJEQ0I2Z1lJS3dZQkJRVUhBUUVFZ2Qwd2dkb3dhd1lJS3dZQkJRVUhNQUtHDQpYMmgwZEhBNkx5OWpZWEp2YjNReExuTmxjblpwZW1rdVlXeHNhWFIxWkdVdWFYUXZVRXRKTFVGc2JHbDBkV1JsDQpMMEZzYkdsMGRXUmxKVEl3VW05dmRDVXlNRU5sY25ScFptbGpZWFJwYjI0bE1qQkJkWFJvYjNKcGRIa3VZM0owDQpNR3NHQ0NzR0FRVUZCekFDaGw5b2RIUndPaTh2WTJGeWIyOTBNaTV6WlhKMmFYcHBMbUZzYkdsMGRXUmxMbWwwDQpMMUJMU1MxQmJHeHBkSFZrWlM5QmJHeHBkSFZrWlNVeU1GSnZiM1FsTWpCRFpYSjBhV1pwWTJGMGFXOXVKVEl3DQpRWFYwYUc5eWFYUjVMbU55ZERBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQUdFM3Y4N2xwRm4rVGNYS0s2ei9kDQo5QWZJNEwvdUpIaUpkYlorSHRJU1hrcGxVS280cUxKZzVJSUtYMFlGYUlWN1ZyLzE5djE1MlZQU25ZT3hja01XDQpGQkVZVHQ5aWpFQkszSUFZK1JMOVZ6MnhaNG5ZREluK2lxaStNU2ZydW83RTBSMkNaSWlxSzBIOXBiWDJXdDZhDQordWtPVmVaTlFnZmpVLzBHQVBaMmVlVGlkZGJ5d0UxNmt2WTFpZEpQSTlzUTVGTXNoWWtRNUI5S2dCVUpTMlQ1DQpxLzYvRXMyTEdhWEUwQUJpbEp0azROMXhvZUFvaGlWbXJUdWhVWmY2WVoxQ1pnMnRES0dDeDFMVC9UOVlCOU93DQpPUkYvSFhaU0k5NjRyOTNOcEEwOG10QU52S3QzRDUweGtTaUF3N01PL1pHUkpkTnp4UXVubTgydERYbE9jWkdXDQoyb3lIT2ZGVFJSSFl4R1IxclBSNkJTSUlucW9BTjFqY3B0WVBDc01LMDFHVlh4dUtQNFFNODJ3SnRRVmhpZkF1DQpMMHgvNGFTaGFnTVk3bHhhVkdXd0hEZkUvOVNCdmt5QXdkdFEwSUJ3RG95WnJiWVRPVURuQTJVWStla2RIalBuDQpCSXpDWUhEZVhTYU1pV3BqbllhRTNKQVVwKys5OWdmRDE1dUY5UFBzTWNOQ0NXWHplZmVZRGtyM0ZHalBOK3BTDQpUdGNmbmVEanNpV2ZyVlJyamptQ0RiOHBFTWVUc0JHRmdYTlFFdHBmTHRqc2E0bloyZzNpMCtuSWVJMXdIY3FUDQo1RUp5VEhPZW1uTHlYdVE3SUJGM21QUGZNOFRoRERxMGJsOWlNa0ExVEpYeUpQYklrdURmZDlOa2VhVVc0dWRMDQpDMkQrcHRGVkRoTjFYWU9lME1WUElHVT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQ0KTUlJR0hUQ0NCQVdnQXdJQkFnSVFhZ2hqemFWNHhMWkRRdUVWb2VxKzFUQU5CZ2txaGtpRzl3MEJBUXNGQURDQg0KbnpFTE1Ba0dBMVVFQmhNQ1NWUXhEakFNQmdOVkJBZ1RCVWwwWVd4NU1ROHdEUVlEVlFRSEV3WlVjbVZ1ZEc4eA0KSlRBakJnTlZCQXNUSEVScGNtVjZhVzl1WlNCVVpXTnVhV05oSUZSbFkyNXZiRzluYVdVeEdEQVdCZ05WQkFvVA0KRDBGc2JHbDBkV1JsSUZNdWNDNUJMakV1TUN3R0ExVUVBeE1sUVd4c2FYUjFaR1VnVW05dmRDQkRaWEowYVdacA0KWTJGMGFXOXVJRUYxZEdodmNtbDBlVEFnRncweU1EQTBNVEF4TXpJek5UZGFHQTh5TURVd01EUXhNREV6TXpNMQ0KTmxvd2daOHhDekFKQmdOVkJBWVRBa2xVTVE0d0RBWURWUVFJRXdWSmRHRnNlVEVQTUEwR0ExVUVCeE1HVkhKbA0KYm5Sdk1TVXdJd1lEVlFRTEV4eEVhWEpsZW1sdmJtVWdWR1ZqYm1sallTQlVaV051YjJ4dloybGxNUmd3RmdZRA0KVlFRS0V3OUJiR3hwZEhWa1pTQlRMbkF1UVM0eExqQXNCZ05WQkFNVEpVRnNiR2wwZFdSbElGSnZiM1FnUTJWeQ0KZEdsbWFXTmhkR2x2YmlCQmRYUm9iM0pwZEhrd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJSw0KQW9JQ0FRQ2tmSXdKMXAzajhZTnpYWGtQalAxSXZtWW95bWpQNW9VRC9YWW45S2hJaFJwZnJoRDBUa2FtdHhOZQ0KMW9BWWRqazNrbTNibk9iTkFuV3NMdWQ4NTBONzVIekIzaStkWk9xUUxaUjNDazYwaW9mY2FNbXVWRWFIRGJNZg0Kd3VNUTFJMy9BUUVBRWMrNGRkOHAwQ0xxKzFPeVFZcDBoZ3BvTlhDczBjU2pQbmV0Zk9LejhFTFd1NHhkN3daZA0KUmdvdjFXaUZyTHJLVzgyRnJOSHQ2eld2VVMyWVh3YW9zMlZwOGx1aGdrWmZnQ3VOMldGRDhjalZOTTBrcytGMw0KdEttQy9WZitBSzVnTmNpMVNoaU5xZDZwM1RPalozdmJ1QVNCaEQvcVZUN3NhVy84SGcvLzNBQ1VaZmhmV0cxYw0KRzl1UmFzMmU3NitZT3VwaUMxZ1FjTDV1ZStjbkhHb2FUdXdkZG5lSjl1OHlMZ0ZDSS8rTnRISVN0M1JIbHVoSw0KWTdGQ1FudWRmMENLaDgzMFZseG9WUUt4aVF0SXd0ayt1RzMrcllBYzNnektHbC9CUVMzU05MOUJyQzZFMzZ2MQ0KT0ttcE1Bb2F4MXhqRzhPQkN1WlpITFhybDZjMC9PbWxUTkJ4QkJaS1BoTWJHY2c5cVdpeDdTcUpWSGl4Tnk4Mw0KTzNsTWNzSEx0T2pIMXZFbExEek9QSDRGbnZxT1F3RkthWXdBUjQyUlY1K2hBOTBjL2NSOGlscWVWSjYvemNGVA0KNkNLOUJQaUtCNy9FQUhscnVpaWx1K1MvTkFCb1pTckVXaGxLdCtjdjN5UFRpR1d1TUt5bTdTRk9VL29MRTd4WA0KNlpFQnZSWXJRQWVoYmg2WHFkbVVYVHhQaGYxUWMra0E2cnE2b2trdXQ2bC80dUtaWVFJREFRQUJvMUV3VHpBTA0KQmdOVkhROEVCQU1DQVlZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXFjcDYzc1gwMDQycA0KSVdpeGNPZ0pqOERYOVZJd0VBWUpLd1lCQkFHQ054VUJCQU1DQVFBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQg0KQURHSldGNG5IZUxma1NjY1JTNlpjZGlORUdCN1F6b0tYdnNCT09YT29RU2toTG8zNHprVHhXSGlLQXhaS0duRw0KN3ZySUFDODFSaU5JSVFCaEMrVFpCSFJ4TXc3a09uWGRQUXJhUzJZbFFOZCtzR3NLYkZSUCtIMVhqTjQ1Y0JlZw0Kdm5iMGd6VzhmUUQwQmwxRXA3b2pra2VZQkxpSVZUTWNIa3VZTHI3MHlIb2cveDJkbGw2ZUoyWkU5RVkxdEtrUg0KTE15MW9BRTY2L0g0bit3YTFRTGg1L2xmdTFYS1ZjSUduVkZMSkF1MzRqVFRJRFNCUVJYYzkzY3h6Z0VPWHd1eQ0KQnU0ckNPUnAzVi9WWml3aFdMeXkrSXpBSTl6Umw2UVNvQTMydUN4dVBja1UxTFVnUmdURXNGT3NWdnl1WC96SA0KOUZNQjZGbFNiTXAzc0FrZnhkTk9rZ2FVd3NNYnRSM2VCbVBOTFcyZkdwR0hKMDJjeGlYM0UySVJ0NmRENWRlZA0KSWVSL3REQ3N5L3VvbU1oelBIN3RmdW1rVTBOd2lHMHJPL3Izd0ZmRFVrZXgrV3V6cVRZazRMU2JPYmxGMlhQSQ0Kb0h4QTVJWlgvdGhCcnRlWTdjY2dXMlJiQWxTSzJ1WTRXam1IY0RCTjhiVDl2eXpLcS81NHROWXlYQ1lwOVdidQ0KZk9JRUpUUFA4a1FmZmFIeU02ZGhFQWkyR2tOaitnd2gyQ0M2cG5ZQmhPUVQ1dmhjbG1IajF0dS9hU0JIQnd6RA0KNDIwTlhTLzNjSHFNdWZuYUc2aXZQbEJkNGYxQ2FKU2tRbXoyV3BxU1dPaVgvQjBicmNsaThCd2l0QUpMTDhuSA0KQmcyZlkrcUl4ZGdEczVieDd6N2x2WGdodWV2elh3bHNvU3JlTDc4cHA1QXQNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg==
kind: Secret
metadata:
  name: ca-allitude
  namespace: openshift-logging
type: Opaque
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app.kubernetes.io/instance: cluster-sviluppo-tn-01-definition
  name: instance
  namespace: openshift-logging
spec:
  inputs:
  - application:
      namespaces:
      - external-secret
      - group-sync-operator
      - metallb-system
      - open-cluster-management-addon-observability
      - open-cluster-management-agent
      - open-cluster-management-agent-addon
      - rhacs-operator
    name: infrastructure-extra
  - application:
      namespaces:
      - custody-administration
      - real-estate-administration
      - compliance
      - consumer-banking
      - custody-agreement
      - customer-care
      - customer-data
      - fatture
      - iam
      - invoices-dispatcher
      - legacy-agreement
      - legacy-messages
      - location
      - party-reference
      - payment-execution
      - print
      - product-catalog
      - sib-fe-main
      - relationship-management
    name: cbm-applications
  outputs:
  - name: remoteloki
    secret:
      name: ca-allitude
    type: loki
    url: https://loki.collaudo.enet:8443
  - name: openshift-logforwarding-splunk
    secret:
      name: sviluppo-openshift-logforwarding-splunk 
    type: fluentdForward
    url: tls://sviluppo-openshift-logforwarding-splunk.openshift-logging.svc:24224
  pipelines:
  - inputRefs:
    - cbm-applications
    name: applications-logs
    outputRefs:
    - remoteloki
  - inputRefs:
    - infrastructure
    - infrastructure-extra
    name: infra-logs
    outputRefs:
    - openshift-logforwarding-splunk
  - inputRefs:
    - audit
    name: audit-logs
    outputRefs:
    - openshift-logforwarding-splunk
