apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secret-puller
  namespace: openshift-config
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-external-secrets
  namespace: openshift-config
spec:
  secretStoreRef:
    name: vault-allitude-ocp
    kind: ClusterSecretStore
  target:
    name: vault-api-cert
    template:
      type: kubernetes.io/tls
  dataFrom:
  - extract:
      key: infra-trento-01/certificati/api-server
      decodingStrategy: Auto
---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    oauth-apiserver.openshift.io/secure-token-storage: "true"
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  audit:
    profile: Default
  servingCerts:
    namedCertificates:
    - names:
      - api.fcakit01.infra-cert.enet 
      servingCertificate:
        name: vault-api-cert

