appConfig:
  destinationServer:
    name: "gestione-tn-01"
    url: "https://kubernetes.default.svc"
  revision: main
  forwarding:
    splunk:
      # Specify Splunk HEC Token and Index
      token: 0542dd18-56ae-4e09-b6d0-a7c7632998a0
      hostname: fcvlsf02.log.servizi.allitude.it 
